### ISSUE TITLE
Please specify a watch folder

### ISSUE THREAD

**Issue by jasan-s** [ednjv/YoutubeAutomaticUploader#1]
how do i specifiy the watch folder?

**Comment by ghost** [comment]
You need to create a .env file in the root of the project with the following variables: VIDEO_LOCATION=
VIDEO_DESCRIPTION=

Sorry I haven't had the time to write a proper README.md

**Comment by ghost** [comment]
@jasan-s please review the new changes, I've added a README, they should clarify what you want. Thanks for submitting your questions!

**Comment by jasan-s** [comment]
thanks @evasquez26 for the read me. I like the change of env variable of credentials. **Also would love an example.**  My use case is that I need to upload multiple videos with custom thumbnails, descriptions, and tags. If possible could you expand a bit more on how to achieve this.

**Comment by ghost** [comment]
Hi @jasan-s currently there's no way to to achieve what you want but it's in my scope, we do not handle custom thumbnails and tags for each video but we do handle multiple uploads.

In the near future we will be able to configure all of this and I will create a npm package to make it even more usable. Thanks for your input :smile: 

As for the example, suppose you have this folder structure:

```
├─ FolderToUploadVideos
├─ YoutubeAutomaticUploader
|    ├── otherProjectFiles
|    └── .env
├─ credentials.json
```

On your `.env` file you should have

```
VIDEO_LOCATION=../FolderToUploadVideos
CREDENTIALS_LOCATION=../credentials.json
```

you can use absolute paths too
